# pull the official docker image
FROM tiangolo/uvicorn-gunicorn:python3.11-slim

# install dependencies
COPY Pipfile.lock .
COPY Pipfile .
RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --system --deploy
RUN pipenv install --dev

# copy project
COPY . /server/
