version: '3.11'

services:
  web:
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - TZ=Africa/Johannesburg
    build:
      context: .
      dockerfile: docker/server/Dockerfile.traefik
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
    networks:
      - default
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8000:8000
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external: true
